### ISSUE TITLE
Fungerar ej med aktnamn med å i

### ISSUE THREAD

**Issue by bennyjonsson** [Lantmateriet/AktDirektExampleClient#1]
Exempel 12-håt-93
https://abc.def.hi/arkenproxyclient/simpleFetchDocument?county=12&document=12-H%c5T-83

**Comment by christer** [comment]
Åtgärdat
Ändrat teckenkodning för /arkenproxyclient/simpleFetchDocument
Satt teckenkodning till iso8859-1 för att vara bakåtkompatibelt med ArkenProxy.
